#!/usr/bin/env bash

mkdir -p eids
OLD_IFS="$IFS"
IFS=$'\n'
# NOTE: multiple attempts won't work with this script
for line in $(grep 'Starting executor ID' containers/* | perl -ne 'print if s/^containers\/([^:]+).*Starting executor ID ([0-9]+) on host (.*)/\1 \2 \3/'); do
  container="${line%% *}"
  eid="${line% *}"
  eid="${eid#* }"
  host="${line##* }"
  #echo "$eid -> $container on $host"
  ln -s ../containers/"$container" eids/"$eid"
done
IFS="$OLD_IFS"
