#!/usr/bin/env bash

mkdir -p tids
for f in containers/container_*; do
  #echo "Parsing TIDs from $f"
  for tid in $(perl -ne 'print if s/.* Running task .*\(TID ([0-9]+)\).*/\1/' "$f"); do
    ln -s ../"$f" tids/$tid
  done
done

