#!/usr/bin/env bash

mkdir -p app_masters

idx=0

OLD_IFS="$IFS"
IFS=$'\n'
for f in $(grep -l "${YARN_HELPERS_APP_MASTER_GREP_NEEDLE:-ApplicationAttemptId: }" containers/container_*); do
  echo "Found app_master: $f"
  ln -sf ../"$f" app_masters/
  ln -sf ../"$f" app_masters/$idx
  let idx=$idx+1
done
IFS="$OLD_IFS"

if [ $idx -eq 1 ]; then
  ln -sf app_masters/0 app_master
fi
