#!/usr/bin/env bash

mkdir -p drivers

idx=0

OLD_IFS="$IFS"
IFS=$'\n'
for f in $(grep -l "${YARN_HELPERS_DRIVER_GREP_NEEDLE:-spark.SparkContext}" containers/container_*); do
  echo "Found driver: $f"
  ln -sf ../"$f" drivers/
  ln -sf ../"$f" drivers/$idx
  let idx=$idx+1
done
IFS="$OLD_IFS"

if [ $idx -eq 1 ]; then
  ln -sf drivers/0 driver
fi
