#!/bin/bash

for f in ./container-*; do
  line="$(head -n 1 "$f")"
  if [[ ! "$line" =~ ^Container: ]]; then
    echo "Removing: $f"
    rm -f "$f"
    continue
  fi
  container="${line#Container: }"
  container="${container%% on **}"

  host="${line##* on }"

  if [ ! -z "$YARN_HELPERS_DROP_HOST_SUFFIX_FROM" ]; then
    host="${host%${YARN_HELPERS_DROP_HOST_SUFFIX_FROM}*}"
  fi

  mv "$f" "$container"
  mkdir -p "$host"
  cd "$host"
  ln -s ../"$container"
  cd ..
done

