#!/usr/bin/env bash

# Other scripts can use this script to look up application IDs by the last 4 digits, for example:
#
#   $ yarn-appid 0011                            # will return e.g. application_1416279928169_0011
#   $ yarn-appid application_1416279928169_0011  # also returns application_1416279928169_0011

if [ $# -eq 0 ]; then
  err "Usage: $0 <app id>"
  exit 1
fi

for appid in "$@"; do
  if [[ $appid =~ ^[0-9]{4,}$ ]]; then
    set -e
    if [ -z "$(get-yarn-cluster-id)" ]; then
      yarn-refresh-cluster-id
    fi

    appid="application_$(get-yarn-cluster-id)_${appid}"
  fi

  echo "$appid"
done
