#!/bin/bash

appid="$(yarn-appid "$1")"
shift
if [ $# -gt 0 ]; then
  dest_dir="$1"
else
  dest_dir=./"$appid"
fi

mkdir -p "$dest_dir"
cd "$dest_dir"

if [ -s "./logs" ]; then
  echo "Found existing logs file at $PWD/logs; splitting per-container..."
  split-yarn-logs-per-container ./logs
else
  echo "Downloading logs for $appid and splitting per-container..."
  yarn logs -applicationId "$appid" | split-yarn-logs-per-container
fi

echo "Done downloading; rename and create per-host directories..."
rename-and-link-container-logs

echo "Look for driver containers..."
link-driver-logs

echo "Creating TID symlinks..."
link-tids

