#!/usr/bin/env bash

set -e
dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
stack_traces="$dir/stack-traces/stack_traces.py"

appid="$(yarn-appid "$1")"
shift
yarn-logs "$appid" | "$stack_traces" "$@"
